Cross platform directory path support
kodlamaio-projects/nArchitecture.Gen pull request #3
Opened 2023-08-17 01:04 UTC by klc00

Cross platform directory path support (mac, win, linux)

• The directory path is centralized.
• Added support for directory path Unix based operating systems.

2023-08-21 21:46 UTC, secgin commented
MacOS kullanıyorum, "narchgen generate crud" komutunu kullandığımda aşağıdaki gibi geçerli dizinden sonraki dizin ayraçları ters olduğu için "Could not find a part of the path" hatası alıyorum.

`/Users/secgin/RiderProjects/DemoProject\src\demoProject\Domain\Entities`

2023-08-22 10:18 UTC, klc00 commented
https://github.com/klc00/nArchitecture.Gen reposunu klonlayın.

2023-10-13 15:08 UTC, muratfirtina commented
@klc00 Teşekkürler sıkıntı çözüldü sizin repoyla.

2023-10-17 19:38 UTC, ahmet-cetinkaya requested changes
Please remove `.DS_Store`  files associated with macOS. and update `.gitignore`. 🙌

2023-10-18 15:40 UTC, klc00 commented
DS_Store dosyalarını kaldırdım. gitignore içine .DS_Store ekledim.

2023-10-19 07:12 UTC, ahmet-cetinkaya approved these changes

2023-10-19 07:18 UTC, merged

2024-03-08 10:34 UTC, mehmetalbyrak commented
Proje oluşturulurken sürekli path hatası aldım. Macosta Rider kullanıyorum. Çözüm önerisi olan var mı?
<img width="939" alt="Screenshot 2024-03-08 at 13 16 24" src="https://github.com/kodlamaio-projects/nArchitecture.Gen/assets/106533819/0df2e21c-a925-47ae-b84d-ba3bdbcbbd70">
<img width="995" alt="Screenshot 2024-03-08 at 13 18 29" src="https://github.com/kodlamaio-projects/nArchitecture.Gen/assets/106533819/bd9d526d-9ac9-4235-b47e-88e713f041bc">

2024-03-08 10:35 UTC, mehmetalbyrak commented
@ahmet-cetinkaya yardımcı olur musunuz Ahmet bey üstteki repoyu klonladım ben.

2024-03-24 19:16 UTC, ahmet-cetinkaya commented
> Proje oluşturulurken sürekli path hatası aldım. Macosta Rider kullanıyorum. Çözüm önerisi olan var mı? <img alt="Screenshot 2024-03-08 at 13 16 24" width="939" src="https://private-user-images.githubusercontent.com/106533819/311202151-0df2e21c-a925-47ae-b84d-ba3bdbcbbd70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMDc4MDksIm5iZiI6MTcxMTMwNzUwOSwicGF0aCI6Ii8xMDY1MzM4MTkvMzExMjAyMTUxLTBkZjJlMjFjLWE5MjUtNDdhZS1iODRkLWJhM2JkYmNiYmQ3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNFQxOTExNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNmU1NzAxZTdkNGY5YzBlYTdkODY3YWU5MTZhYjAzNDJmNzM2NjllYjBhOTY5OGM0Y2Y1M2I2ZTIxMmE0ZTA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GnrPVtAxlpBmfbpPpUAXI_2SJrNBrG3r4tNSHYphDhg"> <img alt="Screenshot 2024-03-08 at 13 18 29" width="995" src="https://private-user-images.githubusercontent.com/106533819/311202272-bd9d526d-9ac9-4235-b47e-88e713f041bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMDc4MDksIm5iZiI6MTcxMTMwNzUwOSwicGF0aCI6Ii8xMDY1MzM4MTkvMzExMjAyMjcyLWJkOWQ1MjZkLTlhYzktNDIzNS1iNDdlLTg4ZTcxM2YwNDFiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNFQxOTExNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMzEzNzA0YWVlY2QzOGYxNGFlMWI5OGQ4OGQ5ZmRjMTg3ZTA2NmE4YWMwYzNkMTJhZTczYmI1ODNhNzU0ZjcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n2cHJbfocoASHbquFebNfqtxJvVp3dXFyl7K7yEeDWc">

I'm sorry for the delay in seeing this. It seems you're using an old version, hence not being able to find the project file as its name has changed. Please install the latest version via Nuget Tool. You can find it here: https://www.nuget.org/packages/NArchitecture.Gen